### ISSUE TITLE
Update Windows Terminal steps

### ISSUE THREAD

**Issue by tanyapowell** [blackcodherbootcamp/setup-guide#2]
The steps for setting up Windows terminal needs extending to include:

- [x] Michael's set up [video tutorial](https://youtu.be/wPmwgMm0plk)
- [x] Installing VS Code via the windows subsystem
- [x] Installing node via the windows subsystem
- [x] Setup home path alias
- [x] Setup and use SSH with GitHub
- [x] Setup default GitBranch on git init
- [x] Persistent SSH keys

**Comment by haelmj** [comment]
Confirmed that SSH keys are persistent on both WSL and Mac. We only need to worry about setting it up and the alternative which is using personal access tokens.
